name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  phpunit:
    name: "PHPUnit (PHP ${{ matrix.php }}, ${{ matrix.dependencies }})"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ["8.4", "8.5"]
        dependencies: [lowest, highest]
    steps:
      - uses: actions/checkout@v7

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: xdebug
          ini-values: memory_limit=-1
          tools: composer:v2

      - uses: ramsey/composer-install@v3
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Run tests
        run: composer test

  phpstan:
    name: "PHPStan"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          ini-values: memory_limit=-1
          tools: composer:v2

      - uses: ramsey/composer-install@v3

      - name: Run static analysis
        run: composer phpstan -- --error-format=github
