name: "PHPStan analysis"

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.4"
          ini-values: memory_limit=-1
          tools: composer:v2
      - name: "Cache dependencies"
        uses: actions/cache@v2
        with:
          path: |
            ~/.composer/cache
            vendor
          key: "php-7.4"
          restore-keys: "php-7.4"
      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress --no-suggest"
      - name: "Static analysis"
        uses: chindit/actions-phpstan@master
